apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: bankforge
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://account-db:5432/accountdb"
  SPRING_DATASOURCE_USERNAME: "account"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bankforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: ghcr.io/harry-zhao-au/bankforge-account-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: account-service-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-db-secret
                  key: password
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 4
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: bankforge
spec:
  selector:
    app: account-service
  ports:
    - port: 8080
      targetPort: 8080
