apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-service-config
  namespace: bankforge
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ledger-db:5432/ledgerdb"
  SPRING_DATASOURCE_USERNAME: "ledger"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: bankforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: ghcr.io/harry-zhao-au/bankforge-ledger-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ledger-service-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ledger-db-secret
                  key: password
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 4
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: bankforge
spec:
  selector:
    app: ledger-service
  ports:
    - port: 8080
      targetPort: 8080
